return {
    version = "1.1",
    luaversion = "5.1",
    orientation = "orthogonal",
    width = 42,
    height = 42,
    tilewidth = 64,
    tileheight = 64,
    properties = {},
    tilesets = {
        {
            name = "tiles",
            firstgid = 1,
            tilewidth = 64,
            tileheight = 64,
            spacing = 6,
            margin = 6,
            image = "../../../../../../Don't Starve Mod Tools/mod_tools/Tiled/dont_starve/tiles.png",
            imagewidth = 512,
            imageheight = 384,
            properties = {},
            tiles = {}
        }
    },
    layers = {
        {
            type = "tilelayer",
            name = "BG_TILES",
            x = 0,
            y = 0,
            width = 42,
            height = 42,
            visible = true,
            opacity = 1,
            properties = {},
            encoding = "lua",
            data = {

                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0,
                0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0,
                6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 6, 0, 0, 0, 0,
                0, 0, 0, 6, 0, 0, 0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0,
                6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 6, 0, 0, 0,
                0, 0, 6, 0, 0, 0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0,
                6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 6, 0, 0, 0,
                0, 0, 6, 0, 0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0,
                6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 6, 6, 6, 6, 6, 0, 6, 0, 0, 0,
                0, 0, 6, 0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0,
                6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 6, 6, 6, 6, 6, 0, 0, 6, 0, 0,
                0, 6, 0, 0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0,
                6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 6, 0, 0,
                0, 6, 0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0,
                6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 6, 0, 0,
                0, 6, 0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0,
                6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 6, 0,
                6, 0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0,
                6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 6,
                0, 0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0,
                6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 6,
                0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0,
                0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 6,
                0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0,
                0, 0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 6,
                0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0,
                0, 0, 0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 2, 2, 2, 6, 6, 6, 0, 6,
                0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0,
                0, 0, 0, 0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 2, 2, 2, 6, 6, 6, 0, 6,
                0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 6, 6, 6, 6, 6, 6, 6, 6, 2, 2, 2, 6, 6, 6, 0, 6,
                0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 6, 6, 6, 6, 6, 6, 6, 2, 2, 2, 6, 6, 6, 0, 6,
                0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 6, 6, 6, 6, 6, 6, 2, 2, 2, 6, 6, 6, 0, 6,
                0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 6, 6, 6, 6, 6, 6, 6, 2, 2, 2, 6, 6, 6, 0, 6,
                0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 6, 6, 6, 6, 6, 6, 6, 6, 2, 2, 2, 6, 6, 6, 0, 6,
                0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 6, 6, 6, 6, 6, 6, 6, 6, 2, 2, 2, 6, 6, 6, 0, 6,
                0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 6, 6, 6, 6, 6, 6, 6, 6, 2, 2, 2, 6, 6, 6, 0, 6,
                0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 6, 6, 6, 6, 6, 6, 6, 6, 2, 2, 2, 6, 6, 6, 0, 6,
                0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 6, 6, 6, 6, 6, 6, 6, 6, 2, 2, 2, 6, 6, 6, 0, 6,
                0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 6, 6, 6, 6, 6, 6, 6, 6, 2, 2, 2, 6, 6, 0, 6, 6,
                6, 0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0,
                0, 0, 0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
            }
        }, {
            type = "objectgroup",
            name = "FG_OBJECTS",
            visible = true,
            opacity = 1,
            properties = {},
            objects = {
                {
                    name = "",
                    type = "beebox",
                    shape = "rectangle",
                    x = 1278,
                    y = 1100,
                    width = 67,
                    height = 60,
                    visible = true,
                    properties = {}
                }, {
                    name = "",
                    type = "beebox",
                    shape = "rectangle",
                    x = 1278,
                    y = 1300,
                    width = 67,
                    height = 60,
                    visible = true,
                    properties = {}
                }, {
                    name = "",
                    type = "beebox",
                    shape = "rectangle",
                    x = 1278,
                    y = 1500,
                    width = 67,
                    height = 60,
                    visible = true,
                    properties = {}
                }, {
                    name = "",
                    type = "beebox",
                    shape = "rectangle",
                    x = 1278,
                    y = 1700,
                    width = 67,
                    height = 60,
                    visible = true,
                    properties = {}
                }, {
                    name = "",
                    type = "beebox",
                    shape = "rectangle",
                    x = 1278,
                    y = 1900,
                    width = 67,
                    height = 60,
                    visible = true,
                    properties = {}
                }, {
                    name = "",
                    type = "flower",
                    shape = "rectangle",
                    x = 1284,
                    y = 1608,
                    width = 56,
                    height = 47,
                    visible = true,
                    properties = {}
                }, {
                    name = "",
                    type = "flower",
                    shape = "rectangle",
                    x = 1284,
                    y = 1608,
                    width = 56,
                    height = 47,
                    visible = true,
                    properties = {}
                }, {
                    name = "",
                    type = "flower",
                    shape = "rectangle",
                    x = 1284,
                    y = 1608,
                    width = 56,
                    height = 47,
                    visible = true,
                    properties = {}
                }, {
                    name = "",
                    type = "flower",
                    shape = "rectangle",
                    x = 1284,
                    y = 1608,
                    width = 56,
                    height = 47,
                    visible = true,
                    properties = {}
                }, {
                    name = "",
                    type = "flower",
                    shape = "rectangle",
                    x = 1284,
                    y = 1608,
                    width = 56,
                    height = 47,
                    visible = true,
                    properties = {}
                }, {
                    name = "",
                    type = "flower",
                    shape = "rectangle",
                    x = 1284,
                    y = 1608,
                    width = 56,
                    height = 47,
                    visible = true,
                    properties = {}
                }, {
                    name = "",
                    type = "flower",
                    shape = "rectangle",
                    x = 1284,
                    y = 1608,
                    width = 56,
                    height = 47,
                    visible = true,
                    properties = {}
                }, {
                    name = "",
                    type = "flower",
                    shape = "rectangle",
                    x = 1284,
                    y = 1608,
                    width = 56,
                    height = 47,
                    visible = true,
                    properties = {}
                }, {
                    name = "",
                    type = "flower",
                    shape = "rectangle",
                    x = 1284,
                    y = 1608,
                    width = 56,
                    height = 47,
                    visible = true,
                    properties = {}
                }, {
                    name = "",
                    type = "flower",
                    shape = "rectangle",
                    x = 1284,
                    y = 1608,
                    width = 56,
                    height = 47,
                    visible = true,
                    properties = {}
                }, {
                    name = "",
                    type = "flower",
                    shape = "rectangle",
                    x = 1284,
                    y = 1608,
                    width = 56,
                    height = 47,
                    visible = true,
                    properties = {}
                }, {
                    name = "",
                    type = "kochosei_house",
                    shape = "rectangle",
                    x = 894,
                    y = 1343,
                    width = 64,
                    height = 64,
                    visible = true,
                    properties = {}
                }, {
                    name = "",
                    type = "flower",
                    shape = "rectangle",
                    x = 1288,
                    y = 1165,
                    width = 44,
                    height = 48,
                    visible = true,
                    properties = {}
                }, {
                    name = "",
                    type = "flower",
                    shape = "rectangle",
                    x = 1288,
                    y = 1165,
                    width = 44,
                    height = 48,
                    visible = true,
                    properties = {}
                }, {
                    name = "",
                    type = "flower",
                    shape = "rectangle",
                    x = 1288,
                    y = 1165,
                    width = 44,
                    height = 48,
                    visible = true,
                    properties = {}
                }, {
                    name = "",
                    type = "flower",
                    shape = "rectangle",
                    x = 1288,
                    y = 1165,
                    width = 44,
                    height = 48,
                    visible = true,
                    properties = {}
                }, {
                    name = "",
                    type = "flower",
                    shape = "rectangle",
                    x = 1288,
                    y = 1165,
                    width = 44,
                    height = 48,
                    visible = true,
                    properties = {}
                }, {
                    id = 2,
                    name = "kocho_lotus2",
                    type = "kocho_lotus2",
                    shape = "rectangle",
                    x = 1251.68,
                    y = 1173.39,
                    width = 12,
                    height = 12,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 3,
                    name = "kocho_lotus2",
                    type = "kocho_lotus2",
                    shape = "rectangle",
                    x = 1251.68,
                    y = 1273.25,
                    width = 12,
                    height = 12,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 4,
                    name = "kocho_lotus2",
                    type = "kocho_lotus2",
                    shape = "rectangle",
                    x = 1251.68,
                    y = 1373.22,
                    width = 12,
                    height = 12,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 5,
                    name = "kocho_lotus2",
                    type = "kocho_lotus2",
                    shape = "rectangle",
                    x = 1251.68,
                    y = 1473.65,
                    width = 12,
                    height = 12,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 6,
                    name = "kocho_lotus2",
                    type = "kocho_lotus2",
                    shape = "rectangle",
                    x = 1251.68,
                    y = 1573.39,
                    width = 12,
                    height = 12,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 7,
                    name = "kocho_lotus2",
                    type = "kocho_lotus2",
                    shape = "rectangle",
                    x = 1251.68,
                    y = 1673.25,
                    width = 12,
                    height = 12,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 8,
                    name = "kocho_lotus2",
                    type = "kocho_lotus2",
                    shape = "rectangle",
                    x = 1251.68,
                    y = 1773.22,
                    width = 12,
                    height = 12,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 9,
                    name = "kocho_lotus2",
                    type = "kocho_lotus2",
                    shape = "rectangle",
                    x = 1251.68,
                    y = 1873.65,
                    width = 12,
                    height = 12,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 12,
                    name = "kocho_lotus2",
                    type = "kocho_lotus2",
                    shape = "rectangle",
                    x = 1356.39,
                    y = 1173.71,
                    width = 12,
                    height = 12,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 13,
                    name = "kocho_lotus2",
                    type = "kocho_lotus2",
                    shape = "rectangle",
                    x = 1356.39,
                    y = 1273.48,
                    width = 12,
                    height = 12,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 14,
                    name = "kocho_lotus2",
                    type = "kocho_lotus2",
                    shape = "rectangle",
                    x = 1356.39,
                    y = 1373.28,
                    width = 12,
                    height = 12,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 15,
                    name = "kocho_lotus2",
                    type = "kocho_lotus2",
                    shape = "rectangle",
                    x = 1356.39,
                    y = 1473.31,
                    width = 12,
                    height = 12,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 16,
                    name = "kocho_lotus2",
                    type = "kocho_lotus2",
                    shape = "rectangle",
                    x = 1356.39,
                    y = 1573.18,
                    width = 12,
                    height = 12,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 17,
                    name = "kocho_lotus2",
                    type = "kocho_lotus2",
                    shape = "rectangle",
                    x = 1356.39,
                    y = 1673.9,
                    width = 12,
                    height = 12,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 18,
                    name = "kocho_lotus2",
                    type = "kocho_lotus2",
                    shape = "rectangle",
                    x = 1356.39,
                    y = 1773.71,
                    width = 12,
                    height = 12,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 19,
                    name = "kocho_lotus2",
                    type = "kocho_lotus2",
                    shape = "rectangle",
                    x = 1356.39,
                    y = 1873.48,
                    width = 12,
                    height = 12,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 12,
                    name = "watertree_pillar",
                    type = "watertree_pillar",
                    shape = "rectangle",
                    x = 1288.75,
                    y = 919.75,
                    width = 50.75,
                    height = 50.75,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 14,
                    name = "watertree_pillar",
                    type = "watertree_pillar",
                    shape = "rectangle",
                    x = 606,
                    y = 725,
                    width = 72,
                    height = 72,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 21,
                    name = "kochosei_building_redlantern",
                    type = "kochosei_building_redlantern",
                    shape = "rectangle",
                    x = 872.333,
                    y = 1482.83,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 29,
                    name = "kochosei_building_redlantern",
                    type = "kochosei_building_redlantern",
                    shape = "rectangle",
                    x = 872.333,
                    y = 1664.17,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 38,
                    name = "kochosei_building_redlantern",
                    type = "kochosei_building_redlantern",
                    shape = "rectangle",
                    x = 872.333,
                    y = 1822.34,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 45,
                    name = "kochosei_building_redlantern",
                    type = "kochosei_building_redlantern",
                    shape = "rectangle",
                    x = 996.333,
                    y = 1483.41,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 53,
                    name = "kochosei_building_redlantern",
                    type = "kochosei_building_redlantern",
                    shape = "rectangle",
                    x = 996.333,
                    y = 1664.75,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 62,
                    name = "kochosei_building_redlantern",
                    type = "kochosei_building_redlantern",
                    shape = "rectangle",
                    x = 996.333,
                    y = 1822.92,
                    width = 0,
                    height = 0,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 66,
                    name = "kochosei_wishlamp",
                    type = "kochosei_wishlamp",
                    shape = "rectangle",
                    x = 816,
                    y = 1975.58,
                    width = 14.5,
                    height = 14.5,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 67,
                    name = "kochosei_torigate",
                    type = "kochosei_torigate",
                    shape = "rectangle",
                    x = 898.25,
                    y = 1962.5,
                    width = 17.25,
                    height = 17.25,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 68,
                    name = "kochosei_wishlamp",
                    type = "kochosei_wishlamp",
                    shape = "rectangle",
                    x = 977.917,
                    y = 1970,
                    width = 19.5,
                    height = 19.5,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 69,
                    name = "gravestone",
                    type = "gravestone",
                    shape = "rectangle",
                    x = 312.121,
                    y = 772.727,
                    width = 69.697,
                    height = 69.697,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 71,
                    name = "kochosei_apple_tree",
                    type = "kochosei_apple_tree",
                    shape = "rectangle",
                    x = 185.334,
                    y = 708,
                    width = 58.6667,
                    height = 48,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 72,
                    name = "kochosei_fuji_tree",
                    type = "kochosei_fuji_tree",
                    shape = "rectangle",
                    x = 456,
                    y = 970.667,
                    width = 54.6667,
                    height = 54.6667,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 73,
                    name = "",
                    type = "bienbao",
                    shape = "rectangle",
                    x = 354.667,
                    y = 936,
                    width = 21.3333,
                    height = 17.3333,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 74,
                    name = "",
                    type = "bienbao",
                    shape = "rectangle",
                    x = 366.667,
                    y = 1026.67,
                    width = 22.6667,
                    height = 24,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 75,
                    name = "",
                    type = "bienbao",
                    shape = "rectangle",
                    x = 462.667,
                    y = 908,
                    width = 44,
                    height = 24,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 76,
                    name = "",
                    type = "bienbao",
                    shape = "rectangle",
                    x = 577.333,
                    y = 936,
                    width = 42.6667,
                    height = 22.6667,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 77,
                    name = "",
                    type = "bienbao",
                    shape = "rectangle",
                    x = 580,
                    y = 1025.33,
                    width = 29.3333,
                    height = 32,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 79,
                    name = "",
                    type = "bienbao",
                    shape = "rectangle",
                    x = 470.667,
                    y = 1058.67,
                    width = 34,
                    height = 34,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 85,
                    name = "researchlab2",
                    type = "researchlab2",
                    shape = "rectangle",
                    x = 370,
                    y = 1150,
                    width = 34,
                    height = 34,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 86,
                    name = "researchlab3",
                    type = "researchlab3",
                    shape = "rectangle",
                    x = 520,
                    y = 1150,
                    width = 34,
                    height = 34,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 88,
                    name = "kochosei_apple_tree",
                    type = "kochosei_apple_tree",
                    shape = "rectangle",
                    x = 554.667,
                    y = 534.667,
                    width = 58.6667,
                    height = 48,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 89,
                    name = "kochosei_apple_tree",
                    type = "kochosei_apple_tree",
                    shape = "rectangle",
                    x = 554.667,
                    y = 534.667,
                    width = 58.6667,
                    height = 48,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 90,
                    name = "kochosei_apple_tree",
                    type = "kochosei_apple_tree",
                    shape = "rectangle",
                    x = 862.667,
                    y = 612,
                    width = 58.6667,
                    height = 48,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 96,
                    name = "kochosei_apple_tree",
                    type = "kochosei_apple_tree",
                    shape = "rectangle",
                    x = 982.788,
                    y = 1142.67,
                    width = 58.6667,
                    height = 48,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 97,
                    name = "kochosei_apple_tree",
                    type = "kochosei_apple_tree",
                    shape = "rectangle",
                    x = 928.242,
                    y = 930.545,
                    width = 58.6667,
                    height = 48,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 98,
                    name = "pond_cave",
                    type = "pond_cave",
                    shape = "rectangle",
                    x = 260,
                    y = 1348,
                    width = 57.3333,
                    height = 57.3333,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 101,
                    name = "golden_farm_hoe",
                    type = "golden_farm_hoe",
                    shape = "rectangle",
                    x = 414.75,
                    y = 1433.5,
                    width = 22.6667,
                    height = 22.6667,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 102,
                    name = "golden_farm_hoe",
                    type = "golden_farm_hoe",
                    shape = "rectangle",
                    x = 409.5,
                    y = 1429.75,
                    width = 22.6667,
                    height = 22.6667,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 103,
                    name = "golden_farm_hoe",
                    type = "golden_farm_hoe",
                    shape = "rectangle",
                    x = 409,
                    y = 1429.5,
                    width = 22.6667,
                    height = 22.6667,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 104,
                    name = "golden_farm_hoe",
                    type = "golden_farm_hoe",
                    shape = "rectangle",
                    x = 410.25,
                    y = 1432,
                    width = 22.6667,
                    height = 22.6667,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 106,
                    name = "farm_plow_items",
                    type = "farm_plow_item",
                    shape = "rectangle",
                    x = 400,
                    y = 1503,
                    width = 13.5,
                    height = 13.5,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 107,
                    name = "farm_plow_items",
                    type = "farm_plow_item",
                    shape = "rectangle",
                    x = 401.432,
                    y = 1503.43,
                    width = 13.5,
                    height = 13.5,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 108,
                    name = "farm_plow_items",
                    type = "farm_plow_item",
                    shape = "rectangle",
                    x = 401.432,
                    y = 1503.43,
                    width = 13.5,
                    height = 13.5,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 109,
                    name = "farm_plow_items",
                    type = "farm_plow_item",
                    shape = "rectangle",
                    x = 401.432,
                    y = 1503.43,
                    width = 13.5,
                    height = 13.5,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 110,
                    name = "evergreens",
                    type = "evergreen",
                    shape = "rectangle",
                    x = 1588,
                    y = 1544,
                    width = 60,
                    height = 54,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 112,
                    name = "evergreens",
                    type = "evergreen",
                    shape = "rectangle",
                    x = 1838,
                    y = 1523,
                    width = 60,
                    height = 54,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 113,
                    name = "evergreens",
                    type = "evergreen",
                    shape = "rectangle",
                    x = 1898,
                    y = 1595,
                    width = 60,
                    height = 54,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 114,
                    name = "evergreens",
                    type = "evergreen",
                    shape = "rectangle",
                    x = 1788,
                    y = 1341,
                    width = 60,
                    height = 54,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 116,
                    name = "evergreens",
                    type = "evergreen",
                    shape = "rectangle",
                    x = 1598,
                    y = 1419,
                    width = 60,
                    height = 54,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 117,
                    name = "evergreens",
                    type = "evergreen",
                    shape = "rectangle",
                    x = 1524,
                    y = 1877,
                    width = 60,
                    height = 54,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 118,
                    name = "evergreens",
                    type = "evergreen",
                    shape = "rectangle",
                    x = 1676,
                    y = 1687,
                    width = 60,
                    height = 54,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 119,
                    name = "evergreens",
                    type = "evergreen",
                    shape = "rectangle",
                    x = 1858,
                    y = 1843,
                    width = 60,
                    height = 54,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 120,
                    name = "evergreens",
                    type = "evergreen",
                    shape = "rectangle",
                    x = 1534,
                    y = 1255,
                    width = 60,
                    height = 54,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 122,
                    name = "koalefant_winter",
                    type = "koalefant_winter",
                    shape = "rectangle",
                    x = 1937.42,
                    y = 1030.3,
                    width = 72.7273,
                    height = 72.7273,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 123,
                    name = "koalefant_winter",
                    type = "koalefant_winter",
                    shape = "rectangle",
                    x = 1751.27,
                    y = 996.243,
                    width = 72.7273,
                    height = 72.7273,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 124,
                    name = "koalefant_winter",
                    type = "koalefant_winter",
                    shape = "rectangle",
                    x = 2051.27,
                    y = 1249.58,
                    width = 72.7273,
                    height = 72.7273,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 125,
                    name = "koalefant_winter",
                    type = "koalefant_winter",
                    shape = "rectangle",
                    x = 1950.27,
                    y = 862.576,
                    width = 72.7273,
                    height = 72.7273,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 126,
                    name = "koalefant_winter",
                    type = "koalefant_winter",
                    shape = "rectangle",
                    x = 1761.81,
                    y = 653.091,
                    width = 72.7273,
                    height = 72.7273,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 127,
                    name = "koalefant_winter",
                    type = "koalefant_winter",
                    shape = "rectangle",
                    x = 1509.09,
                    y = 866.667,
                    width = 72.7273,
                    height = 72.7273,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 135,
                    name = "grass",
                    type = "grass",
                    shape = "rectangle",
                    x = 588.174,
                    y = 1105.7,
                    width = 18,
                    height = 18,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 136,
                    name = "grass",
                    type = "grass",
                    shape = "rectangle",
                    x = 588,
                    y = 1105.5,
                    width = 18,
                    height = 18,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 137,
                    name = "grass",
                    type = "grass",
                    shape = "rectangle",
                    x = 588.333,
                    y = 1105.67,
                    width = 18,
                    height = 18,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 138,
                    name = "grass",
                    type = "grass",
                    shape = "rectangle",
                    x = 588.333,
                    y = 1105.67,
                    width = 18,
                    height = 18,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 139,
                    name = "grass",
                    type = "grass",
                    shape = "rectangle",
                    x = 588.333,
                    y = 1105.67,
                    width = 18,
                    height = 18,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 140,
                    name = "grass",
                    type = "grass",
                    shape = "rectangle",
                    x = 588.333,
                    y = 1105.67,
                    width = 18,
                    height = 18,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 141,
                    name = "grass",
                    type = "grass",
                    shape = "rectangle",
                    x = 588.333,
                    y = 1105.67,
                    width = 18,
                    height = 18,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 142,
                    name = "grass",
                    type = "grass",
                    shape = "rectangle",
                    x = 588.333,
                    y = 1105.67,
                    width = 18,
                    height = 18,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 143,
                    name = "grass",
                    type = "grass",
                    shape = "rectangle",
                    x = 588.333,
                    y = 1105.67,
                    width = 18,
                    height = 18,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 144,
                    name = "grass",
                    type = "grass",
                    shape = "rectangle",
                    x = 588.333,
                    y = 1105.67,
                    width = 18,
                    height = 18,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 145,
                    name = "grass",
                    type = "grass",
                    shape = "rectangle",
                    x = 588.333,
                    y = 1105.67,
                    width = 18,
                    height = 18,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 146,
                    name = "grass",
                    type = "grass",
                    shape = "rectangle",
                    x = 588.333,
                    y = 1105.67,
                    width = 18,
                    height = 18,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 147,
                    name = "grass",
                    type = "grass",
                    shape = "rectangle",
                    x = 588.333,
                    y = 1105.67,
                    width = 18,
                    height = 18,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 148,
                    name = "sapling",
                    type = "sapling",
                    shape = "rectangle",
                    x = 629.667,
                    y = 1104.67,
                    width = 19.3333,
                    height = 19.3333,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 149,
                    name = "sapling",
                    type = "sapling",
                    shape = "rectangle",
                    x = 627.667,
                    y = 1104.67,
                    width = 19.3333,
                    height = 19.3333,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 150,
                    name = "sapling",
                    type = "sapling",
                    shape = "rectangle",
                    x = 627.667,
                    y = 1104.67,
                    width = 19.3333,
                    height = 19.3333,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 151,
                    name = "sapling",
                    type = "sapling",
                    shape = "rectangle",
                    x = 627.667,
                    y = 1104.67,
                    width = 19.3333,
                    height = 19.3333,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 152,
                    name = "sapling",
                    type = "sapling",
                    shape = "rectangle",
                    x = 627.667,
                    y = 1104.67,
                    width = 19.3333,
                    height = 19.3333,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 153,
                    name = "sapling",
                    type = "sapling",
                    shape = "rectangle",
                    x = 627.667,
                    y = 1104.67,
                    width = 19.3333,
                    height = 19.3333,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 154,
                    name = "sapling",
                    type = "sapling",
                    shape = "rectangle",
                    x = 627.667,
                    y = 1104.67,
                    width = 19.3333,
                    height = 19.3333,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 155,
                    name = "sapling",
                    type = "sapling",
                    shape = "rectangle",
                    x = 627.667,
                    y = 1104.67,
                    width = 19.3333,
                    height = 19.3333,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 156,
                    name = "sapling",
                    type = "sapling",
                    shape = "rectangle",
                    x = 627.667,
                    y = 1104.67,
                    width = 19.3333,
                    height = 19.3333,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 157,
                    name = "sapling",
                    type = "sapling",
                    shape = "rectangle",
                    x = 627.667,
                    y = 1104.67,
                    width = 19.3333,
                    height = 19.3333,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 158,
                    name = "sapling",
                    type = "sapling",
                    shape = "rectangle",
                    x = 627.667,
                    y = 1104.67,
                    width = 19.3333,
                    height = 19.3333,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 159,
                    name = "sapling",
                    type = "sapling",
                    shape = "rectangle",
                    x = 627.667,
                    y = 1104.67,
                    width = 19.3333,
                    height = 19.3333,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 160,
                    name = "sapling",
                    type = "sapling",
                    shape = "rectangle",
                    x = 627.667,
                    y = 1104.67,
                    width = 19.3333,
                    height = 19.3333,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 161,
                    name = "pond_cave",
                    type = "pond_cave",
                    shape = "rectangle",
                    x = 296.667,
                    y = 1263.33,
                    width = 57.3333,
                    height = 57.3333,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 162,
                    name = "flower",
                    type = "flower",
                    shape = "rectangle",
                    x = 1306,
                    y = 1816.17,
                    width = 9.33333,
                    height = 9.33333,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 163,
                    name = "flower",
                    type = "flower",
                    shape = "rectangle",
                    x = 1305.99,
                    y = 1816.49,
                    width = 9.33333,
                    height = 9.33333,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 164,
                    name = "flower",
                    type = "flower",
                    shape = "rectangle",
                    x = 1305.99,
                    y = 1816.49,
                    width = 9.33333,
                    height = 9.33333,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 165,
                    name = "flower",
                    type = "flower",
                    shape = "rectangle",
                    x = 1305.99,
                    y = 1816.49,
                    width = 9.33333,
                    height = 9.33333,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 166,
                    name = "flower",
                    type = "flower",
                    shape = "rectangle",
                    x = 1305.99,
                    y = 1816.49,
                    width = 9.33333,
                    height = 9.33333,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 167,
                    name = "flower",
                    type = "flower",
                    shape = "rectangle",
                    x = 1305.99,
                    y = 1816.49,
                    width = 9.33333,
                    height = 9.33333,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 168,
                    name = "flower",
                    type = "flower",
                    shape = "rectangle",
                    x = 1305.99,
                    y = 1816.49,
                    width = 9.33333,
                    height = 9.33333,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 169,
                    name = "flower",
                    type = "flower",
                    shape = "rectangle",
                    x = 1305.99,
                    y = 1816.49,
                    width = 9.33333,
                    height = 9.33333,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 170,
                    name = "flower",
                    type = "flower",
                    shape = "rectangle",
                    x = 1305.99,
                    y = 1816.49,
                    width = 9.33333,
                    height = 9.33333,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 171,
                    name = "flower",
                    type = "flower",
                    shape = "rectangle",
                    x = 1305.99,
                    y = 1816.49,
                    width = 9.33333,
                    height = 9.33333,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 172,
                    name = "flower",
                    type = "flower",
                    shape = "rectangle",
                    x = 1305.99,
                    y = 1816.49,
                    width = 9.33333,
                    height = 9.33333,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 173,
                    name = "flower",
                    type = "flower",
                    shape = "rectangle",
                    x = 1305.99,
                    y = 1816.49,
                    width = 9.33333,
                    height = 9.33333,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 174,
                    name = "flower",
                    type = "flower",
                    shape = "rectangle",
                    x = 1309.34,
                    y = 1627.17,
                    width = 9.33333,
                    height = 9.33333,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 175,
                    name = "flower",
                    type = "flower",
                    shape = "rectangle",
                    x = 1309.33,
                    y = 1627.49,
                    width = 9.33333,
                    height = 9.33333,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 176,
                    name = "flower",
                    type = "flower",
                    shape = "rectangle",
                    x = 1309.33,
                    y = 1627.49,
                    width = 9.33333,
                    height = 9.33333,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 177,
                    name = "flower",
                    type = "flower",
                    shape = "rectangle",
                    x = 1309.33,
                    y = 1627.49,
                    width = 9.33333,
                    height = 9.33333,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 178,
                    name = "flower",
                    type = "flower",
                    shape = "rectangle",
                    x = 1309.33,
                    y = 1627.49,
                    width = 9.33333,
                    height = 9.33333,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 179,
                    name = "flower",
                    type = "flower",
                    shape = "rectangle",
                    x = 1309.33,
                    y = 1627.49,
                    width = 9.33333,
                    height = 9.33333,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 180,
                    name = "flower",
                    type = "flower",
                    shape = "rectangle",
                    x = 1309.33,
                    y = 1627.49,
                    width = 9.33333,
                    height = 9.33333,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 181,
                    name = "flower",
                    type = "flower",
                    shape = "rectangle",
                    x = 1309.33,
                    y = 1627.49,
                    width = 9.33333,
                    height = 9.33333,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 182,
                    name = "flower",
                    type = "flower",
                    shape = "rectangle",
                    x = 1309.33,
                    y = 1627.49,
                    width = 9.33333,
                    height = 9.33333,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 183,
                    name = "flower",
                    type = "flower",
                    shape = "rectangle",
                    x = 1309.33,
                    y = 1627.49,
                    width = 9.33333,
                    height = 9.33333,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 184,
                    name = "flower",
                    type = "flower",
                    shape = "rectangle",
                    x = 1309.33,
                    y = 1627.49,
                    width = 9.33333,
                    height = 9.33333,
                    rotation = 0,
                    visible = true,
                    properties = {}
                }, {
                    id = 185,
                    name = "flower",
                    type = "flower",
                    shape = "rectangle",
                    x = 1309.33,
                    y = 1627.49,
                    width = 9.33333,
                    height = 9.33333,
                    rotation = 0,
                    visible = true,
                    properties = {}
                 }, {
                        id =186,
                        name = "kochosei_oc_cmndao",
                        type = "kochosei_oc_cmndao",
                        shape = "rectangle",
                        x = 356,
                        y = 870.667,
                        width = 54.6667,
                        height = 54.6667,
                        rotation = 0,
                        visible = true,
                        properties = {}
                    },
                    {
                        id =187,
                        name = "kochosei_altar",
                        type = "kochosei_altar",
                        shape = "rectangle",
                        x = 1838,
                        y = 1723,
                        width = 60,
                        height = 54,
                        rotation = 0,
                        visible = true,
                        properties = {}
                    }
                }
            }
        }
    }
